-- ═════════════════════════════════════════════════════════════════════════════
-- Vores Kok — Storage: one private bucket for household media.
--
-- Object key layout (generated by packages/domain buildMediaPath, never taken
-- from a client file name):
--     {household_id}/recipes/{recipe_id}/{uuid}.{ext}
--     {household_id}/people/{person_id}/{uuid}.{ext}
-- Access is derived from membership of the household in the first segment.
-- The bucket is private: files are served through short-lived signed URLs.
-- ═════════════════════════════════════════════════════════════════════════════

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'household-media', 'household-media', false, 26214400,
  array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function private.media_path_household(p_name text)
returns uuid
language sql
immutable
set search_path = ''
as $$
  select private.try_uuid((storage.foldername(p_name))[1])
$$;

-- Validates the full key shape so clients cannot write arbitrary paths.
create or replace function private.media_path_is_valid(p_name text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select p_name ~ '^[0-9a-f-]{36}/(recipes|people)/[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp|heic|heif|pdf)$'
$$;

create policy household_media_select on storage.objects for select to authenticated
  using (
    bucket_id = 'household-media'
    and private.has_household_role(private.media_path_household(name), 'viewer')
  );

create policy household_media_insert on storage.objects for insert to authenticated
  with check (
    bucket_id = 'household-media'
    and private.media_path_is_valid(name)
    and private.has_household_role(private.media_path_household(name), 'member')
  );

create policy household_media_update on storage.objects for update to authenticated
  using (
    bucket_id = 'household-media'
    and private.has_household_role(private.media_path_household(name), 'member')
  )
  with check (
    bucket_id = 'household-media'
    and private.media_path_is_valid(name)
    and private.has_household_role(private.media_path_household(name), 'member')
  );

create policy household_media_delete on storage.objects for delete to authenticated
  using (
    bucket_id = 'household-media'
    and private.has_household_role(private.media_path_household(name), 'member')
  );
